### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by EvelynNeverGiveUp** [Neuron-Hackathon/neuron_hackathon_2022#3]
1. For the competition, are we using real e-scooter data collected in Singapore or simulation data with hidden demand distribution? Will our plan be evaluated with one set of data or a series of data samples?
2. As shown on the website, every time we submit a plan, the corresponding reward on the selected date will be given. Is it a fixed date for every shift plan we submit or a random one out of a week?
3. Is there any capacity limit for the van?
4. Since we plan for a whole week in advance, there is a lot of uncertainty. What if we want to retrieve 10 scooters but there are only 3 left? Similarly, if we want to deploy 5 scooters with only 3 left?
5. Can we bring scooters to the warehouse and deploy them in the next period? Is there any available scooters stored in the warehouse and does it take time to retrieve scooters in the warehouse?

**Comment by Neuron-Hackathon** [comment]
1. For the competition, are we using real e-scooter data collected in Singapore or simulation data with hidden demand distribution? Will our plan be evaluated with one set of data or a series of data samples? **We are using processed e-scooter data from one of our markets (but not Singapore). Not sure what your definitions of ‘one set of data’ and ‘a series of data samples’ are. The shift plan will be evaluated against real e-scooter demand data for the testing period.**

2. As shown on the website, every time we submit a plan, the corresponding reward on the selected date will be given. Is it a fixed date for every shift plan we submit or a random one out of a week? **It is a fixed selection of dates within a week.**

3. Is there any capacity limit for the van? **No capacity limit for the first round.**

4. Since we plan for a whole week in advance, there is a lot of uncertainty. What if we want to retrieve 10 scooters but there are only 3 left? Similarly, if we want to deploy 5 scooters with only 3 left? **If you want to retrieve 10 scooters but only 3 left, then you can only retrieve 3. If you want to deploy 5 scooters but only 3 scooters left in the van, you can only deploy 3. Alternatively, you need to get 2 more from the nearby grids.**

5. Can we bring scooters to the warehouse and deploy them in the next period? Is there any available scooters stored in the warehouse and does it take time to retrieve scooters in the warehouse? **Yes, you can bring scooters to the warehouse and load some of them to the van at the beginning of the next shift. And you can assume there are unlimited scooters stored in the warehouse. The time to load scooters from warehouse at the beginning of each shift is not counted towards shift hours. But do keep in mind that you can’t deploy more than the permit cap.**
